import { spawnSync } from "node:child_process";
import { createHash } from "node:crypto";
import { existsSync, readFileSync, readdirSync } from "node:fs";
import { resolve } from "node:path";
import { gzipSync } from "node:zlib";

import { describe, expect, it } from "vitest";
import { z } from "zod";

import manifest from "@/features/catalog/region-map-manifest.generated.json";
import locations from "@/i18n/locations.generated.json";
import navigationVocabulary from "../../contracts/database-engine/portal/navigation-vocabulary.json";

/**
 * The region-map layers are generated by `scripts/maps/build-region-maps.mjs` and are the only thing
 * the browser draws: every path is already projected, so a re-fitted or truncated asset cannot be
 * caught at runtime. These checks therefore assert against the generated bytes themselves.
 *
 * Long loops collect every offender and assert once, so a failure names all of them instead of only
 * the first. The checks are hermetic; reproducing the bytes from the vendored sources is `--check`'s
 * job, which needs the pinned mapshaper binary. The last test runs it when that toolchain is
 * present, and reports a skip when it is not.
 */
const GENERATOR = resolve("scripts/maps/build-region-maps.mjs");
const LOCAL_TOOLCHAIN = resolve("scripts/maps/.toolchain/node_modules/.bin/mapshaper");
const LAYER_GZIP_BUDGET_BYTES = 150 * 1024;
const PATH = resolve("public/maps");

const layerSchema = z.object({
  url: z.string().regex(/^\/maps\/[a-z0-9-]+\.[0-9a-f]{16}\.json$/),
  sha256: z.string().regex(/^[0-9a-f]{64}$/),
  gzipBytes: z.number().int().positive().max(LAYER_GZIP_BUDGET_BYTES),
});

const manifestSchema = z.object({
  schemaVersion: z.literal("portal.region-map-manifest.v1"),
  layers: z.record(z.string(), layerSchema),
  unmapped: z.array(z.object({ layer: z.string(), nodeId: z.string(), reason: z.string().min(1) })),
  sources: z.array(
    z.object({
      id: z.string(),
      url: z.string().url(),
      sha256: z.string().regex(/^[0-9a-f]{64}$/),
      license: z.string(),
    }),
  ),
  licenses: z.record(
    z.string(),
    z.object({ name: z.string(), termsUrl: z.string().url(), terms: z.string().min(1) }),
  ),
});

const featureSchema = z.object({
  boundaryId: z.string().min(1),
  nodeId: z
    .string()
    .regex(/^geo:[a-z0-9-]+$/)
    .nullable(),
  path: z.string().min(1),
});

const layerFileSchema = z.object({
  viewBox: z.string().regex(/^-?\d+ -?\d+ \d+ \d+$/),
  features: z.array(featureSchema).min(1),
});

type Layer = z.infer<typeof layerFileSchema>;
type Feature = z.infer<typeof featureSchema>;

const receipt = manifestSchema.parse(manifest);
const knownCodes = new Set(Object.keys(locations));
const layerKeys = Object.keys(receipt.layers);
const chinaCityKeys = layerKeys.filter((key) => key.startsWith("geo:cn-"));

function layerBytes(layerKey: string) {
  return readFileSync(resolve("public", receipt.layers[layerKey]!.url.replace(/^\//, "")));
}

const parsed = new Map<string, Layer>();
function parsedLayer(layerKey: string) {
  const cached = parsed.get(layerKey);
  if (cached) return cached;
  const layer = layerFileSchema.parse(JSON.parse(layerBytes(layerKey).toString("utf8")));
  parsed.set(layerKey, layer);
  return layer;
}

function viewBox(layerKey: string) {
  const [minX, minY, width, height] = parsedLayer(layerKey).viewBox.split(" ").map(Number) as [
    number,
    number,
    number,
    number,
  ];
  return { minX, minY, width, height };
}

function namedFeatures(layerKey: string): Feature[] {
  return parsedLayer(layerKey).features.filter((feature) => feature.nodeId !== null);
}

describe("region map manifest", () => {
  it("declares a hashed layer under the gzip budget for every administrative family", () => {
    expect(receipt.schemaVersion).toBe("portal.region-map-manifest.v1");
    expect(layerKeys).toContain("world");
    expect(layerKeys).toContain("geo:cn");
    expect(chinaCityKeys.length).toBeGreaterThan(20);
  });

  it("references exactly the layer files that are checked in", () => {
    const onDisk = readdirSync(PATH)
      .filter((name) => name.endsWith(".json"))
      .sort();
    const declared = layerKeys.map((key) => receipt.layers[key]!.url.split("/").pop()!).sort();

    expect(onDisk).toStrictEqual(declared);
  });

  it("matches every layer file against its recorded hash, size and url", () => {
    const broken: string[] = [];
    for (const layerKey of layerKeys) {
      const entry = receipt.layers[layerKey]!;
      const bytes = layerBytes(layerKey);
      const sha256 = createHash("sha256").update(bytes).digest("hex");
      const expectedUrl = `/maps/${layerKey.replace(/:/g, "-")}.${sha256.slice(0, 16)}.json`;

      if (sha256 !== entry.sha256) broken.push(`${layerKey}: sha256 ${sha256} != ${entry.sha256}`);
      if (entry.url !== expectedUrl) broken.push(`${layerKey}: url ${entry.url} != ${expectedUrl}`);
      const gzipBytes = gzipSync(bytes, { level: 9 }).byteLength;
      if (gzipBytes !== entry.gzipBytes) {
        broken.push(`${layerKey}: gzipBytes ${gzipBytes} != ${entry.gzipBytes}`);
      }
    }
    expect(broken).toStrictEqual([]);
  });

  it("keeps each layer a filled, integer-only path set inside its own viewBox", () => {
    const broken: string[] = [];
    for (const layerKey of layerKeys) {
      const { minX, minY, width, height } = viewBox(layerKey);
      for (const feature of parsedLayer(layerKey).features) {
        const where = `${layerKey} ${feature.boundaryId}`;
        const keys = Object.keys(feature).sort();
        if (keys.join(",") !== "boundaryId,nodeId,path")
          broken.push(`${where}: keys ${keys.join(",")}`);
        if (!/^(M-?\d+ -?\d+(?:L-?\d+ -?\d+)+Z)+$/.test(feature.path)) {
          broken.push(`${where}: path is not a closed polygon set`);
          continue;
        }
        const numbers = feature.path.match(/-?\d+/g)!.map(Number);
        for (let index = 0; index < numbers.length; index += 2) {
          const [x, y] = [numbers[index]!, numbers[index + 1]!];
          const inside = x >= minX && x <= minX + width && y >= minY && y <= minY + height;
          if (!inside) {
            broken.push(`${where}: ${x} ${y} outside viewBox ${parsedLayer(layerKey).viewBox}`);
            break;
          }
        }
      }
    }
    expect(broken).toStrictEqual([]);
  });

  it("only names canonical location codes, and never invents one", () => {
    const unknown: string[] = [];
    for (const layerKey of layerKeys) {
      for (const feature of parsedLayer(layerKey).features) {
        if (feature.nodeId === null) continue;
        if (!knownCodes.has(feature.nodeId.slice(4).toUpperCase())) {
          unknown.push(`${layerKey} ${feature.boundaryId} -> ${feature.nodeId}`);
        }
      }
    }
    expect(unknown).toStrictEqual([]);
  });

  it("keeps each China node in one shape so a click target is unambiguous", () => {
    const duplicated: string[] = [];
    for (const layerKey of ["geo:cn", ...chinaCityKeys]) {
      const named = namedFeatures(layerKey).map((feature) => feature.nodeId);
      const unique = new Set(named);
      if (unique.size !== named.length) {
        duplicated.push(`${layerKey}: ${named.length} shapes for ${unique.size} nodes`);
      }
    }
    expect(duplicated).toStrictEqual([]);
  });

  it("places every China city node in the province layer that owns it", () => {
    const misplaced: string[] = [];
    for (const layerKey of chinaCityKeys) {
      for (const feature of namedFeatures(layerKey)) {
        if (!feature.nodeId!.startsWith(`${layerKey}-`)) {
          misplaced.push(`${layerKey} ${feature.boundaryId} -> ${feature.nodeId}`);
        }
      }
    }
    const provinceNodes = new Set(namedFeatures("geo:cn").map((feature) => feature.nodeId!));
    expect(provinceNodes.size).toBe(31);
    for (const nodeId of provinceNodes) {
      if (!nodeId.startsWith("geo:cn-")) misplaced.push(`geo:cn -> ${nodeId}`);
    }
    expect(misplaced).toStrictEqual([]);
  });

  it("shares one coordinate space between the province layer and its sublayers", () => {
    const china = viewBox("geo:cn");
    const escaped: string[] = [];
    for (const layerKey of chinaCityKeys) {
      const window = viewBox(layerKey);
      const inside =
        window.minX >= china.minX &&
        window.minY >= china.minY &&
        window.minX + window.width <= china.minX + china.width &&
        window.minY + window.height <= china.minY + china.height;
      if (!inside) escaped.push(`${layerKey}: ${parsedLayer(layerKey).viewBox}`);
    }
    expect(escaped).toStrictEqual([]);
  });
});

describe("region map coverage", () => {
  it("lists the codes that have no boundary instead of forcing them onto a modern shape", () => {
    const unmapped = new Map(receipt.unmapped.map((entry) => [entry.nodeId, entry]));

    // Historic or renamed prefecture names that exist in the dictionary but not in today's
    // boundaries: they must stay unassigned rather than snap onto a successor.
    const historic: Record<string, string> = {
      "geo:cn-ah-cah": "geo:cn-ah", // 巢湖市, abolished 2011
      "geo:cn-sd-lws": "geo:cn-sd", // 莱芜市, merged into 济南 2019
      "geo:cn-hb-xfn": "geo:cn-hb", // 襄樊市, renamed 襄阳市 2010
      "geo:cn-xz-xid": "geo:cn-xz", // 日喀则地区, now 日喀则市
      "geo:cn-nm-cfs": "geo:cn-nm", // 赤峰（乌兰哈达）市, parenthesised name
    };
    const wrong = Object.entries(historic)
      .map(([nodeId, layer]) => ({ nodeId, layer, entry: unmapped.get(nodeId) }))
      .filter(({ layer, entry }) => entry === undefined || entry.layer !== layer)
      .map(({ nodeId }) => nodeId);

    expect(wrong).toStrictEqual([]);
    expect(receipt.unmapped.length).toBeGreaterThanOrEqual(16);
  });

  it("keeps the nine-dash inset and other unnamed shapes without inventing a node for them", () => {
    const unassigned = parsedLayer("geo:cn").features.filter((feature) => feature.nodeId === null);
    const boundaryIds = unassigned.map((feature) => feature.boundaryId);

    expect(boundaryIds).toContain("cnprov:100000_JD");
    // Taiwan, Hong Kong and Macao are top-level dictionary codes, not CN subdivisions, so the
    // province shapes for them carry no node rather than a guessed one.
    expect(boundaryIds).toContain("cnprov:710000");
    expect(boundaryIds).toContain("cnprov:810000");
    expect(boundaryIds).toContain("cnprov:820000");
    expect(boundaryIds.length).toBe(4);
  });

  it("records a usable source receipt for every emitted layer family", () => {
    expect(receipt.sources.length).toBe(layerKeys.length);
    const unlicensed = receipt.sources
      .filter((source) => receipt.licenses[source.license] === undefined)
      .map((source) => source.id);
    expect(unlicensed).toStrictEqual([]);
    const platform = receipt.sources.find((source) => source.id === "world-map-units-50m")!;
    expect(platform.url).toContain("raw.githubusercontent.com/tiangong-lca/platform/");
    expect(platform.url).toContain("297f09843d0974efea6cfa9fba69a998b9f4159d");
  });
});

const mapshaper = process.env.MAPSHAPER_BIN ?? (existsSync(LOCAL_TOOLCHAIN) ? LOCAL_TOOLCHAIN : "");

describe("region map regeneration", () => {
  it("rebuilds the checked-in assets byte for byte from the vendored sources", () => {
    const result = spawnSync(process.execPath, [GENERATOR, "--check"], {
      cwd: process.cwd(),
      encoding: "utf8",
      env: { ...process.env, MAPSHAPER_BIN: mapshaper ?? "" },
      timeout: 180_000,
    });

    expect(result.stderr || result.stdout).toContain("Region-map assets verified");
    expect(result.status).toBe(0);
  }, 190_000); // The offline 29-layer build has its own 180-second child-process bound.
});

describe("Database vocabulary and map layer compatibility", () => {
  it("places every Chinese mapped node beneath the same parent as its drawable layer", () => {
    const nodes = new Map(navigationVocabulary.nodes.map((node) => [node.nodeId, node]));
    const mismatches: string[] = [];
    for (const layerKey of layerKeys.filter((key) => key !== "world")) {
      for (const feature of parsedLayer(layerKey).features) {
        if (!feature.nodeId) continue;
        const node = nodes.get(feature.nodeId);
        if (node?.parentNodeId !== layerKey)
          mismatches.push(`${feature.nodeId}: ${String(node?.parentNodeId)} != ${layerKey}`);
      }
    }
    expect(mismatches).toEqual([]);
  });
});
