import { spawnSync } from "node:child_process";
import { createHash } from "node:crypto";
import { existsSync, readFileSync, readdirSync } from "node:fs";
import { resolve } from "node:path";
import { gunzipSync, gzipSync } from "node:zlib";

import { describe, expect, it } from "vitest";
import { z } from "zod";

import manifest from "@/features/catalog/region-map-manifest.generated.json";
import locations from "@/i18n/locations.generated.json";
import navigationVocabulary from "../../contracts/database-engine/portal/navigation-vocabulary.json";
import databaseManifest from "../../contracts/database-engine/portal/manifest.json";

/**
 * The region-map layers are generated by `scripts/maps/build-region-maps.mjs` and are the only thing
 * the browser draws: every path is already projected, so a re-fitted or truncated asset cannot be
 * caught at runtime. These checks therefore assert against the generated bytes themselves.
 *
 * Long loops collect every offender and assert once, so a failure names all of them instead of only
 * the first. The checks are hermetic; reproducing the bytes from the vendored sources is `--check`'s
 * job, which needs the pinned mapshaper binary. The last test runs it when that toolchain is
 * present, and reports a skip when it is not.
 */
const GENERATOR = resolve("scripts/maps/build-region-maps.mjs");
const LOCAL_TOOLCHAIN = resolve("scripts/maps/.toolchain/node_modules/.bin/mapshaper");
const LAYER_GZIP_BUDGET_BYTES = 150 * 1024;
const PATH = resolve("public/maps");

const layerSchema = z.object({
  url: z.string().regex(/^\/maps\/[a-z0-9-]+\.[0-9a-f]{16}\.json$/),
  sha256: z.string().regex(/^[0-9a-f]{64}$/),
  gzipBytes: z.number().int().positive().max(LAYER_GZIP_BUDGET_BYTES),
});

const manifestSchema = z.object({
  schemaVersion: z.literal("portal.region-map-manifest.v1"),
  layers: z.record(z.string(), layerSchema),
  unmapped: z.array(z.object({ layer: z.string(), nodeId: z.string(), reason: z.string().min(1) })),
  sources: z.array(
    z.object({
      id: z.string(),
      url: z.string().url(),
      sha256: z.string().regex(/^[0-9a-f]{64}$/),
      license: z.string(),
    }),
  ),
  licenses: z.record(
    z.string(),
    z.object({ name: z.string(), termsUrl: z.string().url(), terms: z.string().min(1) }),
  ),
});

const featureSchema = z.object({
  boundaryId: z.string().min(1),
  nodeId: z
    .string()
    .regex(/^geo:[a-z0-9-]+$/)
    .nullable(),
  path: z.string().min(1),
  // Interaction entry only: it never replaces `nodeId`.
  navigationNodeId: z
    .string()
    .regex(/^geo:[a-z0-9-]+$/)
    .optional(),
});

const viewBoxSchema = z.string().regex(/^-?\d+ -?\d+ \d+ \d+$/);

const layerFileSchema = z.object({
  coordinateSpace: z.string().min(1),
  viewBox: viewBoxSchema,
  features: z.array(featureSchema).min(1),
  basemap: z
    .object({
      viewBox: viewBoxSchema,
      land: z.string(),
      borders: z.string().optional(),
      graticule: z.string(),
      frame: z.string().optional(),
    })
    .optional(),
});

type Layer = z.infer<typeof layerFileSchema>;
type Feature = z.infer<typeof featureSchema>;

const receipt = manifestSchema.parse(manifest);
const knownCodes = new Set(Object.keys(locations));
const layerKeys = Object.keys(receipt.layers);
const chinaCityKeys = layerKeys.filter((key) => key.startsWith("geo:cn-"));

function layerBytes(layerKey: string) {
  return readFileSync(resolve("public", receipt.layers[layerKey]!.url.replace(/^\//, "")));
}

const parsed = new Map<string, Layer>();
function parsedLayer(layerKey: string) {
  const cached = parsed.get(layerKey);
  if (cached) return cached;
  const layer = layerFileSchema.parse(JSON.parse(layerBytes(layerKey).toString("utf8")));
  parsed.set(layerKey, layer);
  return layer;
}

function viewBox(layerKey: string) {
  const [minX, minY, width, height] = parsedLayer(layerKey).viewBox.split(" ").map(Number) as [
    number,
    number,
    number,
    number,
  ];
  return { minX, minY, width, height };
}

function viewBoxSize(value: string) {
  const [minX, minY, width, height] = value.split(" ").map(Number) as [
    number,
    number,
    number,
    number,
  ];
  return { minX, minY, width, height };
}

function namedFeatures(layerKey: string): Feature[] {
  return parsedLayer(layerKey).features.filter((feature) => feature.nodeId !== null);
}

describe("region map manifest", () => {
  it("declares a hashed layer under the gzip budget for every administrative family", () => {
    expect(receipt.schemaVersion).toBe("portal.region-map-manifest.v1");
    expect(layerKeys).toContain("world");
    expect(layerKeys).toContain("geo:cn");
    expect(chinaCityKeys.length).toBeGreaterThan(20);
  });

  it("references exactly the layer files that are checked in", () => {
    const onDisk = readdirSync(PATH)
      .filter((name) => name.endsWith(".json"))
      .sort();
    const declared = layerKeys.map((key) => receipt.layers[key]!.url.split("/").pop()!).sort();

    expect(onDisk).toStrictEqual(declared);
  });

  it("matches every layer file against its recorded hash, size and url", () => {
    const broken: string[] = [];
    for (const layerKey of layerKeys) {
      const entry = receipt.layers[layerKey]!;
      const bytes = layerBytes(layerKey);
      const sha256 = createHash("sha256").update(bytes).digest("hex");
      const expectedUrl = `/maps/${layerKey.replace(/:/g, "-")}.${sha256.slice(0, 16)}.json`;

      if (sha256 !== entry.sha256) broken.push(`${layerKey}: sha256 ${sha256} != ${entry.sha256}`);
      if (entry.url !== expectedUrl) broken.push(`${layerKey}: url ${entry.url} != ${expectedUrl}`);
      const gzipBytes = gzipSync(bytes, { level: 9 }).byteLength;
      if (gzipBytes !== entry.gzipBytes) {
        broken.push(`${layerKey}: gzipBytes ${gzipBytes} != ${entry.gzipBytes}`);
      }
    }
    expect(broken).toStrictEqual([]);
  });

  it("keeps each layer a filled, integer-only path set inside its own viewBox", () => {
    const broken: string[] = [];
    for (const layerKey of layerKeys) {
      const { minX, minY, width, height } = viewBox(layerKey);
      for (const feature of parsedLayer(layerKey).features) {
        const where = `${layerKey} ${feature.boundaryId}`;
        const keys = Object.keys(feature).sort().join(",");
        if (keys !== "boundaryId,nodeId,path" && keys !== "boundaryId,navigationNodeId,nodeId,path")
          broken.push(`${where}: keys ${keys}`);
        if (!/^(M-?\d+ -?\d+(?:L-?\d+ -?\d+)+Z)+$/.test(feature.path)) {
          broken.push(`${where}: path is not a closed polygon set`);
          continue;
        }
        const numbers = feature.path.match(/-?\d+/g)!.map(Number);
        for (let index = 0; index < numbers.length; index += 2) {
          const [x, y] = [numbers[index]!, numbers[index + 1]!];
          const inside = x >= minX && x <= minX + width && y >= minY && y <= minY + height;
          if (!inside) {
            broken.push(`${where}: ${x} ${y} outside viewBox ${parsedLayer(layerKey).viewBox}`);
            break;
          }
        }
      }
    }
    expect(broken).toStrictEqual([]);
  });

  it("only names canonical location codes, and never invents one", () => {
    const unknown: string[] = [];
    for (const layerKey of layerKeys) {
      for (const feature of parsedLayer(layerKey).features) {
        if (feature.nodeId === null) continue;
        if (!knownCodes.has(feature.nodeId.slice(4).toUpperCase())) {
          unknown.push(`${layerKey} ${feature.boundaryId} -> ${feature.nodeId}`);
        }
      }
    }
    expect(unknown).toStrictEqual([]);
  });

  it("keeps each China node in one shape so a click target is unambiguous", () => {
    const duplicated: string[] = [];
    for (const layerKey of ["geo:cn", ...chinaCityKeys]) {
      const named = namedFeatures(layerKey).map((feature) => feature.nodeId);
      const unique = new Set(named);
      if (unique.size !== named.length) {
        duplicated.push(`${layerKey}: ${named.length} shapes for ${unique.size} nodes`);
      }
    }
    expect(duplicated).toStrictEqual([]);
  });

  it("places every China city node in the province layer that owns it", () => {
    const misplaced: string[] = [];
    for (const layerKey of chinaCityKeys) {
      for (const feature of namedFeatures(layerKey)) {
        if (!feature.nodeId!.startsWith(`${layerKey}-`)) {
          misplaced.push(`${layerKey} ${feature.boundaryId} -> ${feature.nodeId}`);
        }
      }
    }
    const provinceNodes = new Set(namedFeatures("geo:cn").map((feature) => feature.nodeId!));
    expect(provinceNodes.size).toBe(34);
    for (const nodeId of provinceNodes) {
      if (!nodeId.startsWith("geo:cn-") && !["geo:tw", "geo:hk", "geo:mo"].includes(nodeId))
        misplaced.push(`geo:cn -> ${nodeId}`);
    }
    expect(misplaced).toStrictEqual([]);
  });

  it("shares one coordinate space between the province layer and its sublayers", () => {
    const china = viewBox("geo:cn");
    const escaped: string[] = [];
    for (const layerKey of chinaCityKeys) {
      const window = viewBox(layerKey);
      const inside =
        window.minX >= china.minX &&
        window.minY >= china.minY &&
        window.minX + window.width <= china.minX + china.width &&
        window.minY + window.height <= china.minY + china.height;
      if (!inside) escaped.push(`${layerKey}: ${parsedLayer(layerKey).viewBox}`);
    }
    expect(escaped).toStrictEqual([]);
  });
});

describe("region map coverage", () => {
  it("lists the codes that have no boundary instead of forcing them onto a modern shape", () => {
    const unmapped = new Map(receipt.unmapped.map((entry) => [entry.nodeId, entry]));

    // Historic or renamed prefecture names that exist in the dictionary but not in today's
    // boundaries: they must stay unassigned rather than snap onto a successor.
    const historic: Record<string, string> = {
      "geo:cn-ah-cah": "geo:cn-ah", // 巢湖市, abolished 2011
      "geo:cn-sd-lws": "geo:cn-sd", // 莱芜市, merged into 济南 2019
      "geo:cn-hb-xfn": "geo:cn-hb", // 襄樊市, renamed 襄阳市 2010
      "geo:cn-xz-xid": "geo:cn-xz", // 日喀则地区, now 日喀则市
      "geo:cn-nm-cfs": "geo:cn-nm", // 赤峰（乌兰哈达）市, parenthesised name
    };
    const wrong = Object.entries(historic)
      .map(([nodeId, layer]) => ({ nodeId, layer, entry: unmapped.get(nodeId) }))
      .filter(({ layer, entry }) => entry === undefined || entry.layer !== layer)
      .map(({ nodeId }) => nodeId);

    expect(wrong).toStrictEqual([]);
    expect(receipt.unmapped.length).toBeGreaterThanOrEqual(16);
  });

  it("keeps the nine-dash inset and other unnamed shapes without inventing a node for them", () => {
    const unassigned = parsedLayer("geo:cn").features.filter((feature) => feature.nodeId === null);
    const boundaryIds = unassigned.map((feature) => feature.boundaryId);

    expect(boundaryIds).toContain("cnprov:100000_JD");
    expect(boundaryIds).toEqual(["cnprov:100000_JD"]);
  });

  it("records a usable source receipt for every emitted layer family", () => {
    expect(receipt.sources.length).toBe(layerKeys.length);
    const unlicensed = receipt.sources
      .filter((source) => receipt.licenses[source.license] === undefined)
      .map((source) => source.id);
    expect(unlicensed).toStrictEqual([]);
    const platform = receipt.sources.find((source) => source.id === "world-map-units-50m")!;
    expect(platform.url).toContain("raw.githubusercontent.com/tiangong-lca/platform/");
    expect(platform.url).toContain("297f09843d0974efea6cfa9fba69a998b9f4159d");
  });
});

const mapshaper = process.env.MAPSHAPER_BIN ?? (existsSync(LOCAL_TOOLCHAIN) ? LOCAL_TOOLCHAIN : "");

describe("region map regeneration", () => {
  it("rebuilds the checked-in assets byte for byte from the vendored sources", () => {
    const result = spawnSync(process.execPath, [GENERATOR, "--check"], {
      cwd: process.cwd(),
      encoding: "utf8",
      env: { ...process.env, MAPSHAPER_BIN: mapshaper ?? "" },
      timeout: 180_000,
    });

    expect(result.stderr || result.stdout).toContain("Region-map assets verified");
    expect(result.status).toBe(0);
  }, 190_000); // The offline 29-layer build has its own 180-second child-process bound.
});

describe("Database vocabulary and map layer compatibility", () => {
  it("binds the three reviewed administrative codes to unique source-backed China boundaries", () => {
    const source = JSON.parse(
      gunzipSync(
        readFileSync(resolve("scripts/maps/sources/china-province-100000-full.json.gz")),
      ).toString("utf8"),
    ) as {
      features: {
        properties: { adcode: number; name: string; level: string; parent?: { adcode: number } };
      }[];
    };
    for (const [code, adcode, name] of [
      ["TW", 710000, "台湾省"],
      ["HK", 810000, "香港特别行政区"],
      ["MO", 820000, "澳门特别行政区"],
    ] as const) {
      const nodeId = `geo:${code.toLowerCase()}`;
      expect(navigationVocabulary.nodes.find((node) => node.nodeId === nodeId)).toMatchObject({
        code,
        parentNodeId: "geo:cn",
        dimension: "geography",
      });
      const evidence = source.features.filter((feature) => feature.properties.adcode === adcode);
      expect(evidence).toHaveLength(1);
      expect(evidence[0]!.properties).toMatchObject({
        name,
        level: "province",
        parent: { adcode: 100000 },
      });
      expect(
        parsedLayer("geo:cn").features.find((feature) => feature.boundaryId === `cnprov:${adcode}`),
      ).toMatchObject({ nodeId });
      expect(receipt.layers).not.toHaveProperty(nodeId);
    }
    const declaration = databaseManifest.files.find(
      (file) => file.path === "navigation-vocabulary.json",
    )!;
    const bytes = readFileSync(
      resolve("contracts/database-engine/portal/navigation-vocabulary.json"),
    );
    expect(manifest.contract).toMatchObject({
      sourceCommit: databaseManifest.sourceCommit,
      sourceRepository: databaseManifest.sourceRepository,
      vocabulary: {
        sha256: createHash("sha256").update(bytes).digest("hex"),
        byteLength: bytes.byteLength,
      },
    });
    expect(manifest.contract.vocabulary.sha256).toBe(declaration.sha256);
  });
  it("places every Chinese mapped node beneath the same parent as its drawable layer", () => {
    const nodes = new Map(navigationVocabulary.nodes.map((node) => [node.nodeId, node]));
    const mismatches: string[] = [];
    for (const layerKey of layerKeys.filter((key) => key !== "world")) {
      for (const feature of parsedLayer(layerKey).features) {
        if (!feature.nodeId) continue;
        const node = nodes.get(feature.nodeId);
        if (node?.parentNodeId !== layerKey)
          mismatches.push(`${feature.nodeId}: ${String(node?.parentNodeId)} != ${layerKey}`);
      }
    }
    expect(mismatches).toEqual([]);
  });
});

/**
 * The world layer is Pacific-centred, so its seam falls in the mid-Atlantic and has to be cut by
 * the projection engine. Shifting projected coordinates instead (the shortcut this guards against)
 * leaves a feature that straddles the seam as one ring crossing the whole frame. `ringsOf` reads the
 * emitted path grammar back into rings, and `spaceOf` gives the coordinate space a layer is drawn
 * in: a Chinese sublayer is a window, so its rings are measured against the shared `geo:cn` frame.
 */
function ringsOf(path: string): { left: number; right: number; height: number }[] {
  return path
    .split("M")
    .slice(1)
    .map((subpath) => {
      const numbers = subpath.replace(/Z.*/s, "").match(/-?\d+/g)!.map(Number);
      let left = Infinity;
      let right = -Infinity;
      let top = Infinity;
      let bottom = -Infinity;
      for (let index = 0; index < numbers.length; index += 2) {
        left = Math.min(left, numbers[index]!);
        right = Math.max(right, numbers[index]!);
        top = Math.min(top, numbers[index + 1]!);
        bottom = Math.max(bottom, numbers[index + 1]!);
      }
      return { left, right, height: bottom - top };
    });
}

function spaceOf(layerKey: string) {
  return viewBox(layerKey.startsWith("geo:cn") ? "geo:cn" : "world");
}

describe("region map seam geometry", () => {
  it("cuts the seam in the projection instead of shifting projected coordinates", () => {
    // A ring confined to the polar rim (Antarctica's Robinson edge) may be wide; one that reaches
    // into the map body while spanning half the frame is an uncut seam.
    const spanning: string[] = [];
    for (const layerKey of layerKeys) {
      const space = spaceOf(layerKey);
      for (const feature of parsedLayer(layerKey).features) {
        for (const ring of ringsOf(feature.path)) {
          const width = (ring.right - ring.left) / space.width;
          if (width > 0.5 && ring.height / space.height > 0.1) {
            spanning.push(
              `${layerKey} ${feature.boundaryId}: ring spans ${(width * 100).toFixed(0)}%`,
            );
          }
        }
      }
    }
    expect(spanning).toStrictEqual([]);
  });

  it("centres the world on the Pacific: Asia west of the Americas", () => {
    const space = viewBox("world");
    const centre = (boundaryId: string) => {
      const feature = parsedLayer("world").features.find((item) => item.boundaryId === boundaryId)!;
      const rings = ringsOf(feature.path);
      const left = Math.min(...rings.map((ring) => ring.left));
      const right = Math.max(...rings.map((ring) => ring.right));
      return ((left + right) / 2 - space.minX) / space.width;
    };

    expect(centre("ne50m:CHN")).toBeLessThan(0.5);
    expect(centre("ne50m:USA")).toBeGreaterThan(0.5);
  });

  it("keeps the world seam in the Atlantic, clear of populated continents", () => {
    const space = viewBox("world");
    const onBothEdges: string[] = [];
    for (const feature of parsedLayer("world").features) {
      let left = false;
      let right = false;
      for (const ring of ringsOf(feature.path)) {
        if ((ring.left - space.minX) / space.width < 0.2) left = true;
        if ((ring.right - space.minX) / space.width > 0.8) right = true;
      }
      if (left && right) onBothEdges.push(feature.boundaryId);
    }

    // A feature appears on both edges only because the seam cut it, so this set must not be empty.
    expect(onBothEdges).toContain("ne50m:GRL");
    // A central meridian of 180° would put these here; 150°E must not.
    const slicedContinents = [
      "ne50m:ENG",
      "ne50m:FRA",
      "ne50m:ESP",
      "ne50m:DZA",
      "ne50m:MLI",
      "ne50m:GHA",
      "ne50m:TGO",
      "ne50m:BFA",
    ];
    expect(onBothEdges.filter((id) => slicedContinents.includes(id))).toStrictEqual([]);
  });
});

/**
 * Basemap acceptance. The basemap must be drawn in exactly the same coordinate
 * space as its foreground — same projection, same fitted transform — because a
 * mis-scaled context layer looks plausible while silently misplacing every
 * neighbour. These checks therefore assert *relative* geometry that only holds
 * when foreground and basemap agree, rather than restating numbers.
 */
/** The basemap's geometry fields — `viewBox` is a window, not a path. */
const basemapFields = (layerKey: string) => {
  const basemap = parsedLayer(layerKey).basemap;
  if (!basemap) throw new Error(`${layerKey} has no basemap`);
  return Object.entries(basemap).filter(
    ([name, value]) => name !== "viewBox" && typeof value === "string" && value,
  ) as [string, string][];
};

function boundsOf(path: string) {
  const numbers = path.match(/-?\d+/g)!.map(Number);
  let left = Infinity;
  let top = Infinity;
  let right = -Infinity;
  let bottom = -Infinity;
  for (let index = 0; index < numbers.length; index += 2) {
    left = Math.min(left, numbers[index]!);
    right = Math.max(right, numbers[index]!);
    top = Math.min(top, numbers[index + 1]!);
    bottom = Math.max(bottom, numbers[index + 1]!);
  }
  return { left, top, right, bottom };
}

describe("region map basemap", () => {
  it("declares one shared coordinate space so the camera can be continuous", () => {
    const spaces = new Set(layerKeys.map((layerKey) => parsedLayer(layerKey).coordinateSpace));
    expect([...spaces]).toStrictEqual(["pacific-robinson-v1"]);
  });

  it("covers the whole canvas aspect range with its background window", () => {
    const [minAspect, maxAspect] = [0.75, 4];
    const wrong: string[] = [];
    for (const layerKey of layerKeys) {
      const layer = parsedLayer(layerKey);
      const preferred = viewBox(layerKey);
      const background = viewBoxSize(layer.basemap!.viewBox);
      const contains =
        background.minX <= preferred.minX &&
        background.minY <= preferred.minY &&
        background.minX + background.width >= preferred.minX + preferred.width &&
        background.minY + background.height >= preferred.minY + preferred.height;
      if (!contains) wrong.push(`${layerKey}: background does not contain the preferred window`);
      if (layerKey === "world") {
        // The world's background *is* the map; there is no wider context to cut,
        // so the renderer letterboxes instead of asking for more.
        if (layer.basemap!.viewBox !== layer.viewBox) wrong.push("world: background != viewBox");
        continue;
      }
      if (background.width < preferred.height * maxAspect - 1) {
        wrong.push(`${layerKey}: too narrow for a ${maxAspect}:1 canvas`);
      }
      if (background.height < preferred.width / minAspect - 1) {
        wrong.push(`${layerKey}: too short for a ${minAspect}:1 canvas`);
      }
    }
    expect(wrong).toStrictEqual([]);
  });

  it("nests every window inside its parent's, so zoom levels share one camera", () => {
    const outOfOrder: string[] = [];
    const world = viewBox("world");
    const china = viewBox("geo:cn");
    const inside = (child: ReturnType<typeof viewBox>, parent: ReturnType<typeof viewBox>) =>
      child.minX >= parent.minX &&
      child.minY >= parent.minY &&
      child.minX + child.width <= parent.minX + parent.width &&
      child.minY + child.height <= parent.minY + parent.height;
    for (const layerKey of layerKeys) {
      if (layerKey === "world") continue;
      if (!inside(viewBox(layerKey), world)) outOfOrder.push(`${layerKey} outside world`);
      if (layerKey === "geo:cn") continue;
      if (!inside(viewBox(layerKey), china)) outOfOrder.push(`${layerKey} outside geo:cn`);
    }
    expect(outOfOrder).toStrictEqual([]);
  });

  it("draws every basemap field strictly inside the background window", () => {
    const escaped: string[] = [];
    for (const layerKey of layerKeys) {
      const background = viewBoxSize(parsedLayer(layerKey).basemap!.viewBox);
      for (const [field, path] of basemapFields(layerKey)) {
        const bounds = boundsOf(path);
        const inside =
          bounds.left >= background.minX &&
          bounds.top >= background.minY &&
          bounds.right <= background.minX + background.width &&
          bounds.bottom <= background.minY + background.height;
        if (!inside) escaped.push(`${layerKey}.${field}: ${JSON.stringify(bounds)}`);
      }
    }
    expect(escaped).toStrictEqual([]);
  });

  it("never draws a path around the globe: long context segments sit on the window edge", () => {
    // An uncut seam would show up as one segment spanning most of the *world*,
    // far wider than any legitimate piece of context. Clipped context does have
    // long segments, but they run along the window border, and simplified
    // context has straight chords, but they are a few percent of the world at
    // most — both are distinguished by this threshold.
    const world = viewBox("world");
    const wrapped: string[] = [];
    for (const layerKey of layerKeys) {
      const background = viewBoxSize(parsedLayer(layerKey).basemap!.viewBox);
      const right = background.minX + background.width;
      const bottom = background.minY + background.height;
      const nearEdge = Math.max(background.width, background.height) * 0.01;
      for (const [field, path] of basemapFields(layerKey)) {
        for (const subpath of path.split("M").slice(1)) {
          const numbers = subpath.replace(/Z.*/s, "").match(/-?\d+/g)!.map(Number);
          for (let index = 2; index < numbers.length; index += 2) {
            const [fromX, fromY] = [numbers[index - 2]!, numbers[index - 1]!];
            const [toX, toY] = [numbers[index]!, numbers[index + 1]!];
            if (Math.abs(toX - fromX) <= world.width * 0.5) continue;
            const onHorizontalEdge =
              fromY === toY &&
              (Math.abs(fromY - background.minY) <= nearEdge ||
                Math.abs(fromY - bottom) <= nearEdge);
            const onVerticalEdge =
              fromX === toX &&
              (Math.abs(fromX - background.minX) <= nearEdge ||
                Math.abs(fromX - right) <= nearEdge);
            if (!onHorizontalEdge && !onVerticalEdge) {
              wrapped.push(`${layerKey}.${field}: ${fromX},${fromY} -> ${toX},${toY}`);
            }
          }
        }
      }
    }
    expect(wrapped).toStrictEqual([]);
  });

  it("pre-cuts the shared context wide enough for every declared background window", () => {
    // The bug this pins: the context used to be pre-cut to a multiple of one
    // layer's preferred window, so a wide background window was declared but its
    // far neighbours had already been clipped away — invisible to a containment
    // check, visible as a straight false coastline in the middle of the map.
    const coverage = JSON.parse(
      readFileSync(resolve("scripts/maps/coverage-report.json"), "utf8"),
    ) as { contextWindow: string };
    const context = viewBoxSize(coverage.contextWindow);
    const escaped: string[] = [];
    for (const layerKey of layerKeys) {
      if (layerKey === "world") continue;
      const background = viewBoxSize(parsedLayer(layerKey).basemap!.viewBox);
      const inside =
        background.minX >= context.minX &&
        background.minY >= context.minY &&
        background.minX + background.width <= context.minX + context.width &&
        background.minY + background.height <= context.minY + context.height;
      if (!inside) escaped.push(`${layerKey}: ${parsedLayer(layerKey).basemap!.viewBox}`);
    }
    expect(escaped).toStrictEqual([]);
  });

  it("fills the widest declared window with real neighbours, not a clipped edge", () => {
    // The country layer declares the widest background of all (a 4:1 canvas).
    // Before the pre-cut was widened its land covered only 56% of that window,
    // leaving an empty band where Asia and Europe are.
    const background = viewBoxSize(parsedLayer("geo:cn").basemap!.viewBox);
    const land = boundsOf(parsedLayer("geo:cn").basemap!.land);
    expect((land.right - land.left) / background.width).toBeGreaterThan(0.9);
    expect(land.left).toBeLessThanOrEqual(background.minX + background.width * 0.05);
    expect(land.right).toBeGreaterThanOrEqual(background.minX + background.width * 0.95);
  });

  it("encloses the foreground, proving basemap and foreground share one transform", () => {
    const misaligned: string[] = [];
    for (const layerKey of layerKeys) {
      const space = viewBox(layerKey);
      const foreground = boundsOf(
        parsedLayer(layerKey)
          .features.map((f) => f.path)
          .join(""),
      );
      const context = ["land", "frame", "graticule"]
        .flatMap((field) => basemapFields(layerKey).filter(([name]) => name === field))
        .map(([, path]) => boundsOf(path));
      if (context.length === 0) continue;
      const enclosing = context.some(
        (bounds) =>
          bounds.left <= foreground.left + space.width * 0.02 &&
          bounds.right >= foreground.right - space.width * 0.02 &&
          bounds.top <= foreground.top + space.height * 0.02 &&
          bounds.bottom >= foreground.bottom - space.height * 0.02,
      );
      if (!enclosing) misaligned.push(layerKey);
    }
    expect(misaligned).toStrictEqual([]);
  });

  it("keeps the world graticule on the same Pacific seam as the foreground", () => {
    // Only the graticule is scanned for cross-map segments: the frame's pole
    // edge is legitimately one full-width straight line, and the frame is
    // covered instead by the containment check above (a frame built on the
    // wrong seam collapses towards the centre and cannot enclose the land).
    const space = viewBox("world");
    const jumps: string[] = [];
    const graticule = parsedLayer("world").basemap!.graticule;
    for (const subpath of graticule.split("M").slice(1)) {
      const numbers = subpath.replace(/Z.*/s, "").match(/-?\d+/g)!.map(Number);
      for (let index = 2; index < numbers.length; index += 2) {
        const jump = Math.abs(numbers[index]! - numbers[index - 2]!) / space.width;
        if (jump > 0.25) jumps.push(`${(jump * 100).toFixed(0)}%`);
      }
    }
    expect(jumps).toStrictEqual([]);
  });

  it("gives every regional layer neighbouring land, borders and a receipted grid", () => {
    const missing: string[] = [];
    for (const layerKey of layerKeys) {
      const basemap = parsedLayer(layerKey).basemap;
      if (!basemap) {
        missing.push(`${layerKey}: no basemap`);
        continue;
      }
      if (layerKey === "world") {
        // The world's own foreground is the land, so it ships a frame instead.
        if (!basemap.frame || basemap.land !== "") missing.push("world: frame/land");
        continue;
      }
      if (!basemap.land) missing.push(`${layerKey}: no neighbouring land`);
      if (!basemap.graticule) missing.push(`${layerKey}: no graticule`);
      if (layerKey !== "geo:cn" && !basemap.borders) {
        missing.push(`${layerKey}: no province borders`);
      }
    }
    expect(missing).toStrictEqual([]);
  });

  it("uses the frozen graticule ladder, recorded per layer", () => {
    const params = (
      manifest as {
        basemap?: { graticule?: { world?: number; regionalLadder?: number[] } };
      }
    ).basemap?.graticule;
    expect(params?.world).toBe(30);
    expect(params?.regionalLadder).toStrictEqual([10, 5, 2, 1]);

    const coverage = JSON.parse(
      readFileSync(resolve("scripts/maps/coverage-report.json"), "utf8"),
    ) as { layers: { layer: string; graticuleInterval: number }[] };
    const wrong = coverage.layers
      .filter((entry) =>
        entry.layer === "world"
          ? entry.graticuleInterval !== params?.world
          : !params?.regionalLadder?.includes(entry.graticuleInterval),
      )
      .map((entry) => `${entry.layer}: ${entry.graticuleInterval}`);
    expect(wrong).toStrictEqual([]);
  });
});

/**
 * The world layer answers to one `geo:cn` interaction entry. These checks pin the
 * two things that make that honest: the alias never touches a shape's scientific
 * `nodeId`, and the two South China Sea shapes are copied from layers that already
 * project them rather than redrawn here.
 */
describe("world interaction grouping", () => {
  const worldLayer = () => parsedLayer("world");

  it("aliases exactly three reviewed child shapes, and only as an interaction entry", () => {
    // An alias points a shape that already has an identity at another entry; a
    // borrowed shape has no identity of its own (nodeId null) and is checked next.
    const aliased = worldLayer().features.filter(
      (feature) => feature.navigationNodeId && feature.nodeId !== null,
    );
    expect(
      aliased.map((feature) => [feature.boundaryId, feature.nodeId, feature.navigationNodeId]),
    ).toStrictEqual([
      ["ne50m:HKG", "geo:hk", "geo:cn"],
      ["ne50m:MAC", "geo:mo", "geo:cn"],
      ["ne50m:TWN", "geo:tw", "geo:cn"],
    ]);
    // The mainland already is the entry, so it must not carry a redundant alias.
    expect(worldLayer().features.find((f) => f.boundaryId === "ne50m:CHN")!.nodeId).toBe("geo:cn");
    for (const feature of worldLayer().features) {
      expect(feature.navigationNodeId).not.toBe(feature.nodeId);
    }
  });

  it("borrows exactly two shapes, byte for byte, from layers in the same space", () => {
    const borrowed = worldLayer().features.filter(
      (feature) => feature.navigationNodeId && feature.nodeId === null,
    );
    expect(borrowed.map((feature) => feature.boundaryId)).toStrictEqual([
      "cnprov:100000_JD",
      "datav:460300",
    ]);
    for (const feature of borrowed) {
      expect(feature.nodeId, `${feature.boundaryId} must stay unmapped`).toBeNull();
      expect(feature.navigationNodeId).toBe("geo:cn");
    }
    const source = (layerKey: string, boundaryId: string) =>
      parsedLayer(layerKey).features.find((feature) => feature.boundaryId === boundaryId)!.path;
    expect(borrowed[0]!.path).toBe(source("geo:cn", "cnprov:100000_JD"));
    expect(borrowed[1]!.path).toBe(source("geo:cn-hi", "datav:460300"));
  });

  it("gathers the entry from six shapes without changing any other layer", () => {
    const entry = worldLayer()
      .features.filter((feature) => (feature.navigationNodeId ?? feature.nodeId) === "geo:cn")
      .map((feature) => feature.boundaryId);
    expect(entry).toStrictEqual([
      "cnprov:100000_JD",
      "datav:460300",
      "ne50m:CHN",
      "ne50m:HKG",
      "ne50m:MAC",
      "ne50m:TWN",
    ]);
    expect(worldLayer().features.length).toBe(267);
    const elsewhere = layerKeys
      .filter((layerKey) => layerKey !== "world")
      .filter((layerKey) =>
        parsedLayer(layerKey).features.some((feature) => feature.navigationNodeId !== undefined),
      );
    expect(elsewhere).toStrictEqual([]);
  });

  it("declares the grouping rule and both borrowed shapes in the receipts", () => {
    const interaction = (
      manifest as {
        interaction?: {
          rule?: string;
          aliases?: { boundaryId: string; navigationNodeId: string }[];
          supplements?: { boundaryId: string; from: string; source: string }[];
        };
      }
    ).interaction;
    expect(interaction?.rule).toBe("navigationNodeId ?? nodeId");
    expect(interaction?.aliases).toStrictEqual([
      { boundaryId: "ne50m:HKG", navigationNodeId: "geo:cn" },
      { boundaryId: "ne50m:MAC", navigationNodeId: "geo:cn" },
      { boundaryId: "ne50m:TWN", navigationNodeId: "geo:cn" },
    ]);
    expect(
      interaction?.supplements?.map((item) => `${item.boundaryId}<-${item.from}`),
    ).toStrictEqual(["cnprov:100000_JD<-geo:cn", "datav:460300<-geo:cn-hi"]);
    const coverage = JSON.parse(
      readFileSync(resolve("scripts/maps/coverage-report.json"), "utf8"),
    ) as { interaction?: { supplements?: unknown[] } };
    expect(coverage.interaction?.supplements).toHaveLength(2);
  });

  it("reports the world's emitted shape count, not the count before borrowing", () => {
    const coverage = JSON.parse(
      readFileSync(resolve("scripts/maps/coverage-report.json"), "utf8"),
    ) as {
      layers: {
        layer: string;
        shapes: number;
        mapped: number;
        sourceShapes?: number;
        supplementShapes?: number;
      }[];
    };
    const world = coverage.layers.find((entry) => entry.layer === "world")!;
    const emitted = parsedLayer("world").features;
    // The receipt is written while the world is built, before the borrowed shapes
    // are attached, so it has to be corrected or it under-reports what ships.
    expect(world.shapes).toBe(emitted.length);
    expect(world.mapped).toBe(emitted.filter((feature) => feature.nodeId).length);
    expect(world.sourceShapes).toBe(265);
    expect(world.supplementShapes).toBe(2);
    expect((world.sourceShapes ?? 0) + (world.supplementShapes ?? 0)).toBe(world.shapes);
    const otherLayers = coverage.layers.filter((entry) => entry.layer !== "world");
    expect(otherLayers.every((entry) => entry.supplementShapes === undefined)).toBe(true);
  });

  it("leaves the vendored sources untouched", () => {
    const sources = JSON.parse(
      readFileSync(resolve("scripts/maps/sources/manifest.json"), "utf8"),
    ) as { sources: { id: string; sha256: string; rawBytes: number }[] };
    const drifted: string[] = [];
    for (const source of sources.sources) {
      const bytes = gunzipSync(
        readFileSync(resolve("scripts/maps/sources", `${source.id}.json.gz`)),
      );
      const sha256 = createHash("sha256").update(bytes).digest("hex");
      if (sha256 !== source.sha256 || bytes.byteLength !== source.rawBytes) {
        drifted.push(source.id);
      }
    }
    expect(drifted).toStrictEqual([]);
  });
});
